"use strict";
exports.__esModule = true;
exports.userRouter = void 0;
var express_1 = require("express");
var UserController_1 = require("../controller/UserController");
var auth_1 = require("../middleware/auth");
var order_router_1 = require("./order-router");
exports.userRouter = (0, express_1.Router)();
exports.userRouter.post('/register', UserController_1["default"].register);
exports.userRouter.post('/login', UserController_1["default"].login);
order_router_1.orderRouter.use(auth_1.auth);
exports.userRouter.get('/off/:id', UserController_1["default"].checkOff);
exports.userRouter.get('/showMyProfile/:id', UserController_1["default"].showMyProfile);
exports.userRouter.get('/userRequest/:id', UserController_1["default"].checkRequest);
exports.userRouter.get('/showSellerProfile/:id', UserController_1["default"].showSellerProfile);
exports.userRouter.get('/showPersonal/:id', UserController_1["default"].showProvision);
exports.userRouter.put('/changePassword/:id', UserController_1["default"].changePassword);
exports.userRouter.get('/findByName/:name', UserController_1["default"].findByName);
exports.userRouter.get('/findByGender/:gender', UserController_1["default"].findByGender);
exports.userRouter.get('/findByBirthday/:year', UserController_1["default"].findByBirthday);
exports.userRouter.put('/userAskVip/:id', auth_1.auth, UserController_1["default"].checkAddVip);
exports.userRouter.get('/showVip', auth_1.auth, UserController_1["default"].showVip);
exports.userRouter.get('/showSixSeller', UserController_1["default"].findByTopSixSeller);
exports.userRouter.get('/showSixVip', UserController_1["default"].findByTopSixVip);
exports.userRouter.get('/showTwelfthSeller', auth_1.auth, UserController_1["default"].findByTopTwelfthSeller);
exports.userRouter.get('/showTopFourMalesEightFemales', UserController_1["default"].findByTopFourMalesEightFemales);
